# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = false

# Change command timeout from 500 to 1000 ms
command_timeout = 1000


# Change the default prompt format
#format = """\
#[╭╴](238)$username$env_var\
#$all[╰─](238)$character"""

# Change the default prompt format
format = """\
[[╭╴](purple bold)](238)$username[─](#c6a0f6 bold)$hostname $os[─](#c6a0f6 bold)$shell[─────](#c6a0f6 bold)$git_state$git_branch$git_commit$git_status[─](#c6a0f6 bold)$python[─](#c6a0f6 bold)$sudo[─]$cmd_duration[──────╮](#c6a0f6 bold)
[╰](purple bold)$character$directory[ : ](129)"""


# UserName
[username]
style_user = "white bold"
style_root = "black bold"
format = "🕹️[─](#c6a0f6 bold)[$user](#cad3f5)"
disabled = false
show_always = true 


# PWD Directory
[directory]
truncation_length = 12
truncation_symbol = "…/"


# Command Duration 
[cmd_duration]
disabled=true

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"OmarToolboX" = "🔨"

[character]
success_symbol = "[─► ](10)[─](purple bold)"
error_symbol = "[─►](9)"
disabled=false


[os]
disabled = false
format = "[$symbol]($style)"
style = "bold white"

[os.symbols]
Macos = ""
Linux = " "
Windows = " "


# PC name
[hostname]
ssh_only = false
format =  "[$hostname](#cad3f5)"
trim_at = ".companyname.com"
disabled = false


# Jobs 
[jobs]
symbol = "+ "
number_threshold = 4
symbol_threshold = 0


#GIT Commit
[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "




# GIT Branch
[git_branch]
symbol = "🌱 "
truncation_length = 15
truncation_symbol = ""
format = '[[$branch$symbol](fg:#cad3f5)]($style)'








#GIT State
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

#Gist Status
[git_status]
conflicted = "🏳 "
ahead = "🏎💨 "
behind = "😰 "
diverged = "😵 "
up_to_date = "✓"
untracked = "[‼️](bold red) "
stashed = "📦 "
modified = "📝 "
staged = '[++\($count\)](green)'
renamed = "👅 "
deleted = "🗑 "

#Shell
[shell]
fish_indicator = "🐟"
powershell_indicator = "_"
bash_indicator = "🐚"
zsh_indicator = " 💤"
disabled = false

#Python
[python]
pyenv_version_name = true
symbol = "🐍"
disabled=false

#SUDO
[sudo]
style = "bold green"
symbol = "👩‍💻 "
disabled = false

#TIME
[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-5"
time_range = "10:00:00-14:00:00"


[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"