version: "2.1"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: Gluetun_VPN_PIA
    cap_add:
      - NET_ADMIN
    restart: always

    volumes:
      - ${Master_Path}/gluetun:/gluetun
    ports:
      # Qbittorrent
      - 8080:8080
      #SonARR
      - 8989:8989/tcp
      #RadARR
      - 7878:7878/tcp 
      #ReadARR
      - 8787:8787
      #ProwLARR
      - 9696:9696
      # mylarr
      - 8090:8090
      # liddar
      - 8686:8686
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${PIA_VPN_USER}
      - OPENVPN_PASSWORD=${PIA_VPN_PASSWORD}
      - SERVER_REGIONS=Iceland
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "www.google.com"]
      interval: 20s
      timeout: 10s
      retries: 5

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: always
    labels:
      - deunhealth.restart.on.unhealthy=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent:/config
      - ${Data_Path}:/data
    network_mode: "container:Gluetun_VPN_PIA"
    depends_on:
      gluetun:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "www.google.com"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s

  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: none
    restart: always
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prowlarr:/config
    network_mode: "container:Gluetun_VPN_PIA"
    depends_on:
      gluetun:
        condition: service_healthy

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr:/config
      - ${Data_Path}:/data
    network_mode: "container:Gluetun_VPN_PIA"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr:/config
      - ${Data_Path}:/data
    network_mode: "container:Gluetun_VPN_PIA"


  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./lidarr:/config
      - ${Data_Path}:/data
    network_mode: "container:Gluetun_VPN_PIA"


  # bazarr:
  #   image: lscr.io/linuxserver/bazarr:latest
  #   container_name: bazarr
  #   restart: always
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./bazarr:/config
  #     - ${Data_Path}:/data
  #   network_mode: "container:Gluetun_VPN_PIA"


  # ytdl-sub:
  #   image: ghcr.io/jmbannon/ytdl-sub:latest
  #   container_name: ytdl-sub
  #   restart: always
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - DOCKER_MODS=linuxserver/mods:universal-cron
  #   volumes:
  #     - ./ytdl-sub:/config
  #     - ${1}/youtube:/youtube
  #   networks:
  #     servarrnetwork:
  #       ipv4_address: 172.69.0.8
