version: "2.1"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: Gluetun_VPN_PIA
    cap_add:
      - NET_ADMIN
    restart: always

    volumes:
      - ${Master_Path}/gluetun:/gluetun
    ports:
      # Qbittorrent
      - 8080:8080
      #SonARR
      - 8989:8989/tcp
      #RadARR
      - 7878:7878/tcp 
      #ReadARR
      - 8787:8787
      #ProwLARR
      - 9696:9696
      # mylarr
      - 8090:8090
      # liddar
      - 8686:8686
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${PIA_VPN_USER}
      - OPENVPN_PASSWORD=${PIA_VPN_PASSWORD}
      - SERVER_REGIONS=Iceland

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    network_mode: "container:Gluetun_VPN_PIA"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${Master_Path}/ProwlARR/config:/config

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    restart: always
    network_mode: "container:Gluetun_VPN_PIA"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${Master_Path}/Readarr/config:/config
      - ${Data_Path}/books:/books      # optional
      - ${Data_Path}/downloads:/downloads  # optional

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    network_mode: "container:Gluetun_VPN_PIA"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${Data_Path}/series:/data      # your media
      - ${Master_Path}/Sonarr/config:/config
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${Master_Path}/lidarr/config:/config
      - ${Data_Path}/music:/music #optional
      - ${Data_Path}/downloads:/downloads #optional
    network_mode: "container:Gluetun_VPN_PIA"
    restart: always
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: always
    network_mode: "container:Gluetun_VPN_PIA"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${Master_Path}/Qbit/config:/config
      - ${Data_Path}/downloads:/downloads
