version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    platform: linux/arm64
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"   # Portainer UI (HTTP)
      - "9443:9443"   # Portainer UI (HTTPS)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  portainer_data:
