version: "2.1"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    network_mode: "container:Gluetun_VPN_PIA"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
    volumes:
      - ${Master_Path}/ProwlARR/config:/config

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    restart: always
    network_mode: "container:Gluetun_VPN_PIA"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${Master_Path}/Readarr/config:/config
      - ${Data_Path}/books:/books      # optional
      - ${Data_Path}/downloads:/downloads  # optional

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    network_mode: "container:Gluetun_VPN_PIA"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${Data_Path}/series:/data      # your media
      - ${Master_Path}/Sonarr/config:/config

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${Master_Path}/lidarr/config:/config
      - ${Data_Path}/music:/music #optional
      - ${Data_Path}/downloads:/downloads #optional
    network_mode: "container:Gluetun_VPN_PIA"
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: always
    network_mode: "container:Gluetun_VPN_PIA"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8180
    volumes:
      - ${Master_Path}/Qbit/config:/config
      - ${Data_Path}/downloads:/downloads
